---

apiVersion: v1
kind: Service
metadata:
  name: gpt-hf-service
spec:
  # Expose only within the cluster
  type: ClusterIP
  selector:
    app: gpt-hf-pod
  ports:
    - port: 8000
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gpt-hf-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: gpt.167.172.3.57.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gpt-hf-service
                port:
                  number: 8000