name: CI/CD - FastAPI HuggingFace App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prd

    env:
      IMAGE_NAME: mrdoufy/fastapi-app
      KUBE_DEPLOYMENT: gpt-huggingface
      KUBE_NAMESPACE: default\
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME:latest \
            --push --provenance=false .
    
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        env:
            TRIVY_TIMEOUT: 15m
        with:
            image-ref: ${{ env.IMAGE_NAME }}:latest
            format: 'table'
            exit-code: '1'
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
            scanners: 'vuln'
            skip-dirs: usr/local/lib/python3.9/site-packages/torch/lib

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/$KUBE_DEPLOYMENT \
            gptcontainer=$IMAGE_NAME:latest \
            -n $KUBE_NAMESPACE
          kubectl rollout status deployment/$KUBE_DEPLOYMENT -n $KUBE_NAMESPACE