name: CI/CD - FastAPI HuggingFace K8s

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: mrdoufy/fastapi-app
  KUBE_DEPLOYMENT: gpt-huggingface
  KUBE_NAMESPACE: default

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    environment: prd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push multi-arch image
        run: |
          docker buildx create --use
          IMAGE_TAG=${{ github.run_number }}
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest --push --provenance=false .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

  trivy_scan:
    runs-on: ubuntu-latest
    needs: build_and_push
    environment: prd

    steps:
      - name: Scan image with Trivy
        continue-on-error: true   # Prevent blocking deployment for HIGH-only issues
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_TIMEOUT: 15m
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          scanners: 'vuln'
          ignore-unfixed: true

  deploy_to_k8s:
    runs-on: ubuntu-latest
    needs: trivy_scan
    environment: prd

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/${{ env.KUBE_DEPLOYMENT }} gptcontainer=${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -n ${{ env.KUBE_NAMESPACE }}
          kubectl rollout status deployment/${{ env.KUBE_DEPLOYMENT }} -n ${{ env.KUBE_NAMESPACE }}
